name: Deploy to Remote Server
on: [push]
jobs:
  deploy-project:
    name: Deploy project
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands using key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SECRET }}
          port: 22
          script: |
            mkdir -p /app
            ls -l
        
      - name: Clone project
        uses: actions/checkout@master

      - name : Build docker image
        run: docker build -t react-app:latest .

      - name : Run docker image
        run: docker run -d -p 5173:3000 react-app:latest

      - name: Verify deployment
        run: curl -I http://localhost:5173