name: Deploy to Remote Server
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SECRET }}
        #   port: ${{ secrets.PORT }}
          script: |
            mkdir -p /app
            ls -l | grep /app

      - name: Clone project
        uses: actions/checkout@v7

      - name : Build docker image
        run: docker build -t react-app:latest .

      - name : Run docker image
        run: docker run -d --rm -p 80:3000 react-app:latest